### ISSUE TITLE
Any docs on how best to use stored data in views?

### ISSUE THREAD

**Issue by MichaelCrowcroft** [whitecube/nova-flexible-content#15] opened 2019-03-16 21:47 UTC
Would be good for docs to make it clear the best way to go about accessing the data stored from the flexible fields in views.

**Comment by Nyratas** [comment] 2019-03-26 13:47
Hi @MichaelCrowcroft,

At the moment we're thinking about implementing a trait on models that could cast Flexible attributes directly to Collections containing their Layout instances. The only issue I see right now with this is that it'll only work with [pre-defined preset](https://whitecube.github.io/nova-flexible-content/#/?id=predefined-preset-classes) fields.

In other words, until we can find a good way to improve the manual data parsing, we'll not update the docs.

But this doesn't mean we're not open to suggestions. Let us know how you're doing it and maybe we can give you some handy advice!

**Comment by wimurk** [comment] 2019-05-09 05:36
I created a merge request for this issue. Duplicate of #19 
See merge request #22

**Closed** 2019-05-31 12:55 UTC
Labels: question

**Comment by Nyratas** [comment] 2019-05-31 13:03
@MichaelCrowcroft I just added the `HasFlexible` trait, which can be added to Models (and [nova-page Templates](https://github.com/whitecube/nova-page)) and will help using this package in your app's views. 

The package's README has been updated with some notes on this new trait feature. The full documentation will be updated later.

Cheers!
