### ISSUE TITLE
Date field must be cast to 'date' in Eloquent model

### ISSUE THREAD

**Issue by HeadStudios** [whitecube/nova-flexible-content#364] opened 2022-07-13 09:01 UTC
I get this error when I try to update the Repeater field - https://share.getcloudapp.com/geuREWOq

Here is my code for Repeater fields:
app/Nova/Opps.php
...
```
public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Contact'),
            Text::make('Company'),
            Text::make('Email'),
            TextArea::make('Exec Summary'),
            Flexible::make('Products')
            ->addLayout('Product', 'product_single', [
                Text::make('Product Name'),
                TextArea::make('Product Feature'),
                TextArea::make('Product Benefit')
            ]),
            Flexible::make('Stakeholders')
            ->addLayout('Stakeholder', 'stakehold_single', [
                Text::make('Name'),
                Text::make('Position'),
                TextArea::make('Contact Details'),
                TextArea::make('Responsibility')
            ]),
            Flexible::make('Schedule')
            ->addLayout('Todo', 'schedule_single', [
                Text::make('Activity'),
                TextArea::make('Description'),
                Date::make('Completion')
            ]),
            Flexible::make('Terms')
            ->addLayout('Term', 'term_single', [
                Text::make('Headline'),
                TextArea::make('Description')
            ]),
        ];
    }
```

Note the 'Completion' date in Schedule (this is what's tripping it up)

I do think I cast the date right? This is my Opps model class:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Opps extends Model
{
    use HasFactory;

    protected $table = 'opps';

    protected $casts = ['Completion' => 'date'];


    
}
```

Did I cast correctly.. and in the right place? Why is it still showing that error... and then when i try to edit if it has that date it chokes up - just not sure how to cast dates for repeatable fields. Thanks!
P.S. By the way I should probably - this is like the coolest widget ever... I am humbled before its elegance.

**Comment by toonvandenbos** [comment] 2022-07-18 11:50
Hi @HeadStudios, I'm glad you like our package :)

Regarding the dates issue, I think this may be a duplicate of #171 (solution provided in the comments) ?

**Closed by toonvandenbos** 2022-07-18 11:50 UTC

**Comment by HeadStudios** [comment] 2022-07-18 12:04
Man there's so much solutions there but... this one?
DateTime::make('Date')
                        ->format('DD/MM/YYYY HH:mm')
                        ->resolveUsing(function ($value) {
                            return $value;
                        }),

Also I know this is random and not separate but how do I access data in flexible content during action - like as in $mycollection->flex-container->date.. if that makes sense? Sorry just tired but any input much appreciated. Thank you for your reponse!

**Comment by toonvandenbos** [comment] 2022-07-18 12:16
I'm not sure I understand your question, where exactly do you need to access the layout's data ?

Flexible layouts implement the `HasAttributes` trait, exactly like models, meaning you can access their data as if they were models.

**Comment by HeadStudios** [comment] 2022-07-18 20:34
Ohh ok, I will check it out - and I was going to access it on Creation/Update so I will check out that HasAttribute

**Comment by HeadStudios** [comment] 2022-07-20 12:22
So... I just looked up HasAttributes trait and I only get API from Laravel which doesn't really give an example... 

soo... 

`public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Contact'),
            Text::make('Company'),
            Text::make('Email'),
            TextArea::make('Exec Summary'),
            Flexible::make('Products')
            ->addLayout('Product', 'product_single', [
                Text::make('Product Name'),
                TextArea::make('Product Feature'),
                TextArea::make('Product Benefit')
            ]),
            Flexible::make('Stakeholders')
            ->addLayout('Stakeholder', 'stakehold_single', [
                Text::make('Name'),
                Text::make('Position'),
                TextArea::make('Contact Details'),
                TextArea::make('Responsibility')
            ]),
            Flexible::make('Schedule')
            ->addLayout('Todo', 'schedule_single', [
                Text::make('Activity'),
                TextArea::make('Description')
                //Date::make('Completion')
            ]),
            Flexible::make('Terms')
            ->addLayout('Term', 'term_single', [
                Text::make('Headline'),
                TextArea::make('Description')
            ]),
        ];
    }`

If I want to access Stakeholder ('stakeholder_single')'s Position attribute? Once I get an idea I can setup the rest. Any input much appreciated. Thank you!

**Comment by toonvandenbos** [comment] 2022-07-20 12:28
When/where do you want to access an attribute of one of the groups of the Stakeholder's flexible values ?

**Comment by HeadStudios** [comment] 2022-07-20 12:42
So I imagine I'd setup a Laravel observer or whatever on Update/Create - then I'd take those values and pass them to a class/Controller - I'd probably do it inside the Resource Event in Nova - https://share.getcloudapp.com/nOuXJr6y. Does that make sense... usually I do a 'ping' to a remote API webhook with values just to ensure they're passing through - once I got a value I'm all good. 

Thank you for the quick response btw - hope my reply makes sense.

**Comment by HeadStudios** [comment] 2022-07-20 13:20
Hi, thank you for your response - I guess I was just looking for a sample line of code that would access the Stakeholder>Position of my field on update/create. Thank you for the link to the doc though - from what I understand it would be like:

$position = $layout->flexible('stakeholder_single')->Position;

or what would be after $position = 

does that make sense? Just get overwhelmed with collection, hasAttribute, then in the Docs it's like 'Resolving the field' and so much stuff - I just want to be able to get the value to then do what I need to do with it... I guess it's never that easy.

Anyway any input much appreciated - but I apprecaite your help in either case.

**Comment by HeadStudios** [comment] 2022-07-20 13:20
P.S. And then it says 'hydrated Layouts' - what are hydrated layouts lol - so overwhelming.

**Comment by toonvandenbos** [comment] 2022-07-20 15:31
You need to understand your flexible content's value will always be a collection ( = array). Let's build an example with the information you provided.

First, on your resource's model, we'll implement the automatic [value casting](https://whitecube.github.io/nova-flexible-content/#/?id=with-casts) of our "flexible attributes" as explained in the docs (we'll prefer attribute casting to the `HasFlexible` trait approach because it's the "Laravel 9-ish" way to work):

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Whitecube\NovaFlexibleContent\Value\FlexibleCast;

class MyNovaResourceModel extends Model
{
    protected $casts = [
        'products' => FlexibleCast::class,
        'stakeholders' => FlexibleCast::class,
        'schedule' => FlexibleCast::class,
        'terms' => FlexibleCast::class,
    ];
}
```

Then, when interacting with the model, you'll be able to access these attributes and directly use them as `Whitecube\NovaFlexibleContent\Layouts\Collection` instances, which extend [Laravel's default Collection with all their useful methods](https://laravel.com/docs/9.x/collections). Since the "stakeholders" attribute is such a collection, you'll need to loop on its values in order to find the stakeholder layout ( = "hydrated layout", meaning it is one of the layouts you defined which has been filled with values for one "stakeholder") you're looking for:

```php
$model = MyNovaResourceModel::find(1);

$interestingStakeholder = $model->stakeholders->firstWhere('name', 'john');
```

Of course I'm making this example up, I'm sure you know how to find the stakeholder you're looking for in the collection. What's important here is that the `$interestingStakeholder` variable now contains an instance of a `Whitecube\NovaFlexibleContent\Layouts\Layout` which contains the attributes ( = values for the fields you defined on the "Stakeholder" layout). This means that you now can access the `position` attribute on it:

```php
$position = $interestingStakeholder->position;
```

If you want to write all this in one line as you showed in your response, it would give something like this:

```php
$position = $model->stakeholders->firstWhere('name', 'john')->position;
```

I sincerely hope this helps, I don't think I can help you any further without being hired for a full review of your project, haha.

**Comment by HeadStudios** [comment] 2022-07-20 20:34
Wow, just reading this now - let me try it today. Thank you so much for your follow up and also specific insight, you're amazing! I'm really excited about trying this finally.
