### ISSUE TITLE
Call to undefined method forceFill

### ISSUE THREAD

**Issue by Jaspur** [whitecube/nova-flexible-content#468] opened 2023-07-04 11:56 UTC
For some reason this occurred after updating dependencies:

```{
    "class": "Error",
    "message": "Call to undefined method App\\Nova\\Flexible\\Layouts\\Hero::forceFill()",
    "code": 0,
    "file": "/var/task/vendor/laravel/nova/src/Fields/Field.php:492",
    "trace": [
        "/var/task/vendor/laravel/nova/src/Fields/Field.php:475",
        "/var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php:307",
        "/var/task/vendor/laravel/nova/src/Fields/Field.php:472",
        "/var/task/vendor/laravel/nova/src/Fields/Field.php:457",
        "/var/task/vendor/laravel/nova/src/Fields/Field.php:439",
        "/var/task/vendor/laravel/nova/src/Fields/Field.php:413",
        "/var/task/vendor/whitecube/nova-flexible-content/src/Layouts/Layout.php:381",
```

@toonvandenbos

**Comment by malekmajzoub** [comment] 2023-07-04 16:10
Rollback to an earlier version of laravel nova. The newest version seems to be incompatible with nova-flexible-content. Use version "laravel/nova": "4.25.1".

**Comment by LorenzoSapora** [comment] 2023-07-05 10:55
Currently it's unclear if nova is going to be patched or 3rd party packages are expected to PR fixes.. See replies from the nova team here: https://github.com/whitecube/nova-flexible-content/issues/464

**Comment by MohammadAsafrahOyoun** [comment] 2023-07-05 11:10
I am facing the same problem, I hope to solve it if possible.

**Comment by LorenzoSapora** [comment] 2023-07-05 12:18
@MohammadAsafrahOyoun you can workaround it by rolling back to `v4.25.1`, or fork this repo and change `\stdClass` to `\Laravel\Nova\Support\Fluent`

**Comment by MohammadAsafrahOyoun** [comment] 2023-07-05 12:28
where change fork this repo and change \stdClass to \Laravel\Nova\Support\Fluent ?

**Comment by voidgraphics** [comment] 2023-07-05 12:36
Duplicate of #464

**Closed by voidgraphics** 2023-07-05 12:36 UTC
