### ISSUE TITLE
'Unable to parse incoming Flexible content' error still in v0.1.9

### ISSUE THREAD

**Issue by Bessamu** [whitecube/nova-flexible-content#54] opened 2019-08-13 12:57 UTC
Hi. I have similar problem.

`Unable to parse incoming Flexible content, data should be an array.`

![image](https://user-images.githubusercontent.com/36696244/62943080-56ead580-bde2-11e9-8b39-1e9b5c1e0c32.png)

I updated to 0.1.9 but problem not resolved for me.

My resource have this Flexible field
```php
Flexible::make('Содержание новости', 'body_json')
    ->addLayout('Блок с текстом', 'wysiwyg', [
        Text::make('Заголовок', 'title'),
        NovaTrumbowyg::make('Содержание', 'body')
    ])
    ->addLayout('Youtube видео', 'video', [
        Text::make('Заголовок', 'title'),
        Image::make('Video Thumbnail', 'thumbnail'),
        Text::make('ID видео (YouTube)', 'video'),
        Text::make('Примечание к видео', 'desc')
    ])
    ->button('Добавить блок')
```

_Originally posted by @Bessamu in https://github.com/whitecube/nova-flexible-content/issues/53#issuecomment-520823113_

**Comment by Bessamu** [comment] 2019-08-13 12:59
And here: `Whitecube\NovaFlexibleContent\Flexible` line `261` $value = `"[{"layout":"wysiwyg","key":"355uifo1gx77j9h8umn7w7-wysiwyg","attributes":{"355uifo1gx77j9h8umn7w7-wysiwyg__title":"asda","355uifo1gx77j9h8umn7w7-wysiwyg__body":"1231231"}}]"`

**Comment by Nyratas** [comment] 2019-08-13 13:04
Hi @Bessamu,

Could you provide some more contextual information? 
Is your Flexible field defined on a regular Resource?
Is your Flexible field wrapped inside another field?
Which version of Laravel Nova are you using?

Thank you!

**Comment by Bessamu** [comment] 2019-08-13 13:11
* Is your Flexible field defined on a regular Resource?
  * Yes
* Is your Flexible field wrapped inside another field?
  * No
* Which version of Laravel Nova are you using?
  * 1.2.1

My fields method:
```php
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable()->onlyOnIndex(),
            Date::make('Дата', 'date')->sortable()->creationRules('required'),
            TextWithSlug::make('Заголовок новости', 'header')->slug('Url')
                ->creationRules('required')
                ->sortable(),
            ElementSwitch::make('Активен', 'enabled')
                ->falseLabel('Нет')
                ->trueLabel('Да')
                ->sortable(),
            Slug::make('Url', 'url'),
            Text::make('Мета Заголовок', 'meta_title')->hideFromIndex(),
            Text::make('Мета ключевые слова', 'meta_keywords')->hideFromIndex(),
            Text::make('Мета описание', 'meta_description')->hideFromIndex(),
            NovaTrumbowyg::make('Краткое описание', 'annotation')->options([
                'svgPath' => config('nova.trumbowyg_icons_path')
            ])->hideFromIndex(),
            BelongsToMany::make('Товары', 'products', ProductResource::class)->searchable(),

            Flexible::make('Содержание новости', 'body_json')
                ->addLayout('Блок с текстом', 'wysiwyg', [
                    Text::make('Заголовок', 'title'),
                    NovaTrumbowyg::make('Содержание', 'body')
                ])
                ->addLayout('Youtube видео', 'video', [
                    Text::make('Заголовок', 'title'),
                    Image::make('Video Thumbnail', 'thumbnail'),
                    Text::make('ID видео (YouTube)', 'video'),
                    Text::make('Примечание к видео', 'desc')
                ])
                ->button('Добавить блок')
        ];
    }
```
Thanks for help!

**Comment by Nyratas** [comment] 2019-08-13 13:14
Could you update to Nova 2.0.10 and keep me posted? Thanks!

**Comment by Bessamu** [comment] 2019-08-13 13:16
Ok, hope it will be possible for my half-legacy app

**Comment by Nyratas** [comment] 2019-08-13 13:26
Alright. I'll close this issue as we're not able to reproduce the issue with Nova 2.0.10. However, feel free to open it again if the issue remains on an up-to-date setup.

**Closed by Nyratas** 2019-08-13 13:26 UTC
