### ISSUE TITLE
Add multiple Layouts at once

### ISSUE THREAD

**Issue by JBoenhoff** [whitecube/nova-flexible-content#144] opened 2020-02-17 14:20 UTC
I'm working on a "Form Configurator" with this Field. So I have a nested Flexible Layout with different Presets. I'd like to add all Layouts at once when I add the outer Layout. Following the example I want to have a Text, Street and City Layout when I add the Address Layout. 

Is this possible or any workaround available?

So I have:
`Flexible::make( 'Content' )->preset( FormPreset::class )`

FormPreset.php handle Method:
```
...
$field->addLayout(AddressLayout::class);
...
```

AddressLayout.php
```
public function fields()
    {
        return [
            Flexible::make( 'Address')->preset( FormAddressPreset::class )
        ];
    }
```

FormAddressPreset.php
```
    public function handle( Flexible $field )
    {
        $field->addLayout( TextLayout::class );
        $field->addLayout( StreetLayout::class );
        $field->addLayout( CityLayout::class );
        $field->fullWidth();
    }
```

**Comment by voidgraphics** [comment] 2020-02-17 14:32
Why do you need all that nesting? Seems like it would be confusing to use. Do you need to be able to add multiple cities in your AddressLayout?

I would simply put the fields straight into AddressLayout:

```php
public function fields()
{
    return [
        Text::make(/*...*/),
        Place::make(/*...*/),
        City::make(/*...*/),
    ];
}
```

I am closing since this is a usage related question and not a bug.

**Closed by voidgraphics** 2020-02-17 14:32 UTC

**Comment by JBoenhoff** [comment] 2020-02-17 14:59
Thank you for your reply (and for the great Field!)!

The Reason why I want this Layout is because I want to be able to reorder the fields and delete some if I don't need them. Sometimes I need a Phone-Field but no Street-Field or want to reorder Street and City in a other Way.
So I just thought that there might be a possibility to "add all" Layouts at once, reorder and delete those which I don't need instead adding one by one which I need. 
But this seems to be a special case nobody else needs.
