### ISSUE TITLE
Limiting Custom Layout

### ISSUE THREAD

**Issue by Petoches** [whitecube/nova-flexible-content#199] opened 2020-07-09 13:15 UTC
Hello,

Is there a way to limit a custom layout to a specific number and not the all flexible field ?

Thanks

**Comment by voidgraphics** [comment] 2020-07-09 13:18
Hi, this is planned (duplicate of #3) but has not been added yet to the package. It's definitely a feature we want to add but have not found the time to do so yet.

We would love to accept a PR if anyone wants to give it a try.

**Closed by voidgraphics** 2020-07-09 13:18 UTC

**Comment by Petoches** [comment] 2020-07-11 15:07
https://github.com/whitecube/nova-flexible-content/pull/200
