### ISSUE TITLE
Select fields not displaying default value

### ISSUE THREAD

**Issue by JonathanDoelan** [whitecube/nova-flexible-content#246] opened 2020-12-11 16:22 UTC
Layouts containing a select field …

```
->addLayout(__('layout'), 'layout', [
	Select::make(__('select'), 'select')
		->options($options)
		// Default value is not preselected on update view
		->default($default),
])
```

… do not display default values on update views!

**Comment by ahinkle** [comment] 2021-04-12 16:03
Duplicate of #242.

**Closed** 2021-04-13 12:18 UTC
