### ISSUE TITLE
Call to a member function getMedia() on array

### ISSUE THREAD

**Issue by iventru** [whitecube/nova-flexible-content#37] opened 2019-07-03 06:29 UTC
I use "Ebess\AdvancedNovaMediaLibrary" for images gallery and got error: Call to a member function getMedia() on array

Code:

 Flexible::make('Gallery')
                ->addLayout('Simple content section', 'wysiwyg', [
                    Images::make('Computer case', 'computer-image-case')
                        ->conversionOnIndexView('thumb')
]

Flexible without Images::make work fine. Images::make without Flexible work fine.

**Comment by voidgraphics** [comment] 2019-07-03 08:22
Duplicate of #33

**Closed by voidgraphics** 2019-07-03 08:22 UTC
Labels: bug, duplicate
