### ISSUE TITLE
Extending Flexible() is broken (foreach error)

### ISSUE THREAD

**Issue by ahinkle** [whitecube/nova-flexible-content#142] opened 2020-01-30 03:38 UTC
Hi,

There is an unnoted breaking change in https://github.com/whitecube/nova-flexible-content/pull/132/files. 

I'm injecting data into the collection once it's retrieved. I'm getting a Invalid argument supplied for foreach() error (when it's been working before this update.)

Before update: `$flexible = $this->attributes[$attribute];`

after update: `$flexible = data_get($this, $attribute);`

Before it would return the json object now it returns null.

I'm extending the `Flexible` method to inject data into the collection:
```
public function getContentAttribute()
    {
        return $this->bladeComponent($this->flexible('content'));
    }
```

```
    /**
     * Inject the Blade Component data into the Content.
     *
     * @param  string  $collection
     * @return string
     */
    public function bladeComponent($collection)
    {
        if (empty($collection) || is_string($collection)) {
            return $collection;
        }

        $collection->map(function ($component) {
            if (class_exists($componentClass = '\\App\\Nova\\Components\\'. str_replace('-', '', Str::title(Str::snake($component->name()))) .'Component')) {
                $componentClass = new $componentClass();

                $component->bladeComponent = $componentClass;

                return $component;
            }
        });

        return $collection;
    }

```

Ref #131

**Comment by voidgraphics** [comment] 2020-02-04 14:50
Hi @ahinkle, so what you're saying is that the call to `$this->flexible('content')` returns null when it should not? How can I reproduce the issue?

**Comment by hgrimelid** [comment] 2020-02-10 21:13
@voidgraphics I'm experiencing a similar problem here.

I've created a nested setup as described in [this comment](https://github.com/whitecube/nova-flexible-content/issues/103#issuecomment-545823283) in issue #103 (extending `SlideshowLayout` in `SlideLayout`).

Nova error: Maximum function nesting level of '256' reached, aborting!

Reverting back to the old code before #131, my Nova panel works as expected.

**Comment by voidgraphics** [comment] 2020-02-11 08:41
The problem lies here:

```php
public function getContentAttribute()
{
    return $this->bladeComponent($this->flexible('content'));
}
```

If you rename the `getContentAttribute` method, it will stop looping infinitely. Sorry we failed to mention this breaking change. We will discuss this internally to see if it's worth keeping the `data_get` or not.

**Comment by ahinkle** [comment] 2020-02-12 03:23
The issue here is that it was working just fine _before_ the change. The change was made and it wasn’t documented or a major version change. Multiple people are reporting the same issue. 

Unit tests would help catch these things and unfortunately there doesn’t appear to be any within this package.

**Comment by voidgraphics** [comment] 2020-02-12 08:39
I'm well aware of these things, and I have apologised in my previous message.

**Comment by SquareBeard** [comment] 2020-03-19 15:48
> We will discuss this internally to see if it's worth keeping the `data_get` or not.

What about #158 ? It looks like a good fix to me.

**Comment by voidgraphics** [comment] 2020-04-30 20:33
Indeed, closing this as it will be fixed by that PR in the next release.

**Closed by voidgraphics** 2020-04-30 20:33 UTC
